name: Update Authlete IdP OpenAPI Specification

on:
  schedule:
    # Run daily at 2:30 AM UTC to check for updates
    - cron: "30 2 * * *"
  workflow_dispatch:
  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-idp-openapi-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: Check current IdP OpenAPI spec info
        id: current-spec
        run: |
          if [ -f "resources/idp-openapi-spec.json" ]; then
            CURRENT_VERSION=$(jq -r '.info.version // "unknown"' resources/idp-openapi-spec.json)
            CURRENT_PATHS=$(jq '.paths | length' resources/idp-openapi-spec.json)
            echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "current-paths=$CURRENT_PATHS" >> $GITHUB_OUTPUT
            echo "Current IdP spec version: $CURRENT_VERSION, paths: $CURRENT_PATHS"
          else
            echo "current-version=none" >> $GITHUB_OUTPUT
            echo "current-paths=0" >> $GITHUB_OUTPUT
            echo "No existing IdP OpenAPI spec found"
          fi

      - name: Update IdP OpenAPI specification
        id: update-spec
        run: |
          echo "Updating IdP OpenAPI specification..."
          uv run python scripts/update_idp_openapi_spec.py

          # Check if IdP OpenAPI spec was changed
          if git diff --quiet resources/idp-openapi-spec.json resources/idp-openapi-spec.yaml; then
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in IdP OpenAPI specification"
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in IdP OpenAPI specification"

            # Get new spec info
            NEW_VERSION=$(jq -r '.info.version // "unknown"' resources/idp-openapi-spec.json)
            NEW_PATHS=$(jq '.paths | length' resources/idp-openapi-spec.json)
            echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "new-paths=$NEW_PATHS" >> $GITHUB_OUTPUT
            echo "New IdP spec version: $NEW_VERSION, paths: $NEW_PATHS"
          fi

      - name: Create Pull Request
        if: steps.update-spec.outputs.has-changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore: update Authlete IdP OpenAPI specification

            - Updated from Authlete IdP API (https://dev-idp.authlete.net/v3/api-docs.yaml)
            - Version: ${{ steps.current-spec.outputs.current-version }} → ${{ steps.update-spec.outputs.new-version }}
            - Paths: ${{ steps.current-spec.outputs.current-paths }} → ${{ steps.update-spec.outputs.new-paths }}
            - Added both YAML and JSON formats for reference

            Auto-generated by update-idp-openapi-spec workflow
          branch: update-idp-openapi-spec-${{ github.run_number }}
          delete-branch: true
          title: "chore: update Authlete IdP OpenAPI specification to v${{ steps.update-spec.outputs.new-version }}"
          body: |
            ## Authlete IdP OpenAPI Specification Update

            This PR updates the Authlete IdP OpenAPI specification from the latest IdP API documentation.

            **Changes:**
            - **Version:** `${{ steps.current-spec.outputs.current-version }}` → \
              `${{ steps.update-spec.outputs.new-version }}`
            - **API Endpoints:** `${{ steps.current-spec.outputs.current-paths }}` → \
              `${{ steps.update-spec.outputs.new-paths }}`
            - **Source:** https://dev-idp.authlete.net/v3/api-docs.yaml

            **Files Updated:**
            - `resources/idp-openapi-spec.yaml` - IdP OpenAPI specification (YAML format)
            - `resources/idp-openapi-spec.json` - IdP OpenAPI specification (JSON format)

            **Context:**
            The Authlete IdP API currently supports limited operations with `ORGANIZATION_ACCESS_TOKEN`:
            - Service creation (`create_service`, `create_service_detailed`)
            - Service deletion (`delete_service`)

            This specification serves as a reference for future IdP API integrations and \
            potential expansion of MCP server capabilities.

            **Verification:**
            - [ ] IdP OpenAPI spec is valid YAML/JSON
            - [ ] Spec contains expected Authlete IdP API endpoints
            - [ ] No breaking changes in existing endpoint definitions
            - [ ] Both YAML and JSON formats are correctly generated

            ---

            🤖 This PR was automatically created by the `update-idp-openapi-spec` GitHub Action.

            **Review Guidelines:**
            1. Verify the changes are legitimate updates from Authlete IdP
            2. Check that service creation/deletion endpoints are preserved
            3. Ensure the new version is correctly parsed
            4. Consider how this spec could be used for future IdP API tool enhancements
          labels: |
            dependencies
            automation
            documentation
            idp-api
          reviewers: |
            watahani

      - name: Summary
        run: |
          if [ "${{ steps.update-spec.outputs.has-changes }}" = "true" ]; then
            echo "✅ Authlete IdP OpenAPI spec updated successfully"
            echo "📊 Version: ${{ steps.current-spec.outputs.current-version }} → \
              ${{ steps.update-spec.outputs.new-version }}"
            echo "🔧 Paths: ${{ steps.current-spec.outputs.current-paths }} → ${{ steps.update-spec.outputs.new-paths }}"
            echo "📋 PR created with both YAML and JSON formats"
            echo "🔧 Available for reference in future IdP API integrations"
          else
            echo "ℹ️ Authlete IdP OpenAPI spec is already up to date"
          fi
